# ==============================================================================
# 02_deseq2_differential_expression.R
#
# Cleaned DESeq2 workflow for Chaetoceros muelleri RNA-seq.
#
# Raw RNA-seq data:
#   NCBI BioProject PRJNA1420504
#
# Inputs:
#   results/counts/Chaetoceros_featureCounts.txt
#   sample_metadata_PRJNA1420504.csv
#
# Differential-expression criteria used in the historical analysis:
#
#   Overall DEG set:
#       P < 0.05 and |log2FoldChange| >= 1
#
#   Direction-specific subsets used for selecting up/down genes:
#       Upregulated:   padj < 0.05 and log2FoldChange >= 1
#       Downregulated: padj < 0.05 and log2FoldChange <= -1
#
# Thus, the directional UP/DOWN sets are intentionally more stringent subsets
# of the broader overall DEG set.
# ==============================================================================

required_packages <- c("DESeq2")

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required R package(s): ",
    paste(missing_packages, collapse = ", "),
    "\nInstall DESeq2 with BiocManager before running this script."
  )
}

suppressPackageStartupMessages({
  library(DESeq2)
})


# ==============================================================================
# 0. CONFIGURATION
# ==============================================================================

count_file <- file.path(
  "results",
  "counts",
  "Chaetoceros_featureCounts.txt"
)

metadata_file <- "sample_metadata_PRJNA1420504.csv"

output_dir <- file.path(
  "results",
  "deseq2"
)

# Historical low-expression filters.
ROW_MEAN_MIN <- 1
MIN_COUNT <- 5
MIN_SAMPLES <- 3

# Differential-expression thresholds.
LFC_CUTOFF <- 1
P_CUTOFF <- 0.05
PADJ_CUTOFF <- 0.05

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(output_dir, "all_contrasts"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(output_dir, "DEG_ALL_P005_LFC1"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(output_dir, "DEG_UP_PADJ005_LFC1"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(output_dir, "DEG_DOWN_PADJ005_LFC1"), recursive = TRUE, showWarnings = FALSE)


# ==============================================================================
# 1. READ SAMPLE METADATA
# ==============================================================================

metadata <- read.csv(
  metadata_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

required_metadata_columns <- c(
  "sample_id",
  "condition",
  "strain_legacy",
  "biological_replicate"
)

missing_meta <- setdiff(
  required_metadata_columns,
  colnames(metadata)
)

if (length(missing_meta) > 0) {
  stop(
    "Metadata is missing required column(s): ",
    paste(missing_meta, collapse = ", ")
  )
}

if (anyDuplicated(metadata$sample_id)) {
  stop("sample_id values in metadata must be unique.")
}


# ==============================================================================
# 2. READ FEATURECOUNTS OUTPUT
# ==============================================================================

fc <- read.delim(
  count_file,
  header = TRUE,
  comment.char = "#",
  check.names = FALSE,
  stringsAsFactors = FALSE
)

required_fc_columns <- c(
  "Geneid",
  "Chr",
  "Start",
  "End",
  "Strand",
  "Length"
)

if (!all(required_fc_columns %in% colnames(fc))) {
  stop(
    "The count file does not look like a standard featureCounts output.\n",
    "Expected columns include: ",
    paste(required_fc_columns, collapse = ", ")
  )
}

count_columns <- setdiff(
  colnames(fc),
  required_fc_columns
)

count_data <- as.matrix(
  fc[, count_columns, drop = FALSE]
)

storage.mode(count_data) <- "integer"
rownames(count_data) <- fc$Geneid

# Convert featureCounts BAM-column names to the clean sample IDs generated by
# 01_align_and_featurecounts.sh.
clean_count_names <- basename(colnames(count_data))
clean_count_names <- sub(
  "\\.sorted\\.bam$",
  "",
  clean_count_names
)

colnames(count_data) <- clean_count_names

missing_samples <- setdiff(
  metadata$sample_id,
  colnames(count_data)
)

extra_samples <- setdiff(
  colnames(count_data),
  metadata$sample_id
)

if (length(missing_samples) > 0) {
  stop(
    "Samples in metadata but not in count matrix: ",
    paste(missing_samples, collapse = ", ")
  )
}

if (length(extra_samples) > 0) {
  warning(
    "Count matrix contains samples not listed in metadata; they will be ignored: ",
    paste(extra_samples, collapse = ", ")
  )
}

count_data <- count_data[
  ,
  metadata$sample_id,
  drop = FALSE
]


# ==============================================================================
# 3. LOW-EXPRESSION FILTERING
# ==============================================================================

# Historical filter 1:
#   rowMeans(countData) > 1
keep_mean <- rowMeans(count_data) > ROW_MEAN_MIN

count_data_filtered <- count_data[
  keep_mean,
  ,
  drop = FALSE
]

# Historical filter 2:
#   at least three samples have >= 5 reads
keep_count <- rowSums(
  count_data_filtered >= MIN_COUNT
) >= MIN_SAMPLES

count_data_filtered <- count_data_filtered[
  keep_count,
  ,
  drop = FALSE
]

filter_summary <- data.frame(
  step = c(
    "Raw genes",
    paste0("rowMeans(count) > ", ROW_MEAN_MIN),
    paste0(
      "count >= ",
      MIN_COUNT,
      " in >= ",
      MIN_SAMPLES,
      " samples"
    )
  ),
  genes_retained = c(
    nrow(count_data),
    sum(keep_mean),
    nrow(count_data_filtered)
  )
)

write.csv(
  filter_summary,
  file.path(
    output_dir,
    "filtering_summary.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 4. RUN DESEQ2
# ==============================================================================

metadata$condition <- factor(
  metadata$condition
)

col_data <- data.frame(
  row.names = metadata$sample_id,
  condition = metadata$condition
)

dds <- DESeqDataSetFromMatrix(
  countData = count_data_filtered,
  colData = col_data,
  design = ~ condition
)

dds <- DESeq(dds)

normalized_counts <- counts(
  dds,
  normalized = TRUE
)

write.csv(
  data.frame(
    gene_id = rownames(normalized_counts),
    normalized_counts,
    check.names = FALSE
  ),
  file.path(
    output_dir,
    "normalized_counts.csv"
  ),
  row.names = FALSE
)

write.csv(
  metadata,
  file.path(
    output_dir,
    "sample_metadata_used.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 5. BUILD THE HISTORICAL CONTRAST SET AUTOMATICALLY
# ==============================================================================

condition_info <- unique(
  metadata[
    ,
    c(
      "condition",
      "strain_legacy"
    )
  ]
)

available_conditions <- unique(
  as.character(metadata$condition)
)

contrast_list <- list()


# ------------------------------------------------------------------------------
# 5A. Within-strain comparisons versus the corresponding 0-h baseline
# ------------------------------------------------------------------------------

for (i in seq_len(nrow(condition_info))) {

  numerator <- condition_info$condition[i]
  strain <- condition_info$strain_legacy[i]

  if (grepl("_0H$", numerator)) {
    next
  }

  denominator <- paste0(
    strain,
    "_0H"
  )

  if (denominator %in% available_conditions) {
    contrast_list[[length(contrast_list) + 1]] <- data.frame(
      contrast_type = "within_strain_vs_0H",
      numerator = numerator,
      denominator = denominator,
      stringsAsFactors = FALSE
    )
  }
}


# ------------------------------------------------------------------------------
# 5B. Each non-WT strain versus WT under the matched treatment/time
# ------------------------------------------------------------------------------

for (i in seq_len(nrow(condition_info))) {

  numerator <- condition_info$condition[i]
  strain <- condition_info$strain_legacy[i]

  if (strain == "WT") {
    next
  }

  suffix <- sub(
    paste0("^", strain, "_?"),
    "",
    numerator
  )

  if (suffix == "0H") {
    denominator <- "WT_0H"
  } else {
    denominator <- paste0(
      "WT_",
      suffix
    )
  }

  if (denominator %in% available_conditions) {
    contrast_list[[length(contrast_list) + 1]] <- data.frame(
      contrast_type = "matched_WT",
      numerator = numerator,
      denominator = denominator,
      stringsAsFactors = FALSE
    )
  }
}

contrast_manifest <- unique(
  do.call(
    rbind,
    contrast_list
  )
)

contrast_manifest$contrast_name <- paste0(
  contrast_manifest$numerator,
  "_vs_",
  contrast_manifest$denominator
)

write.csv(
  contrast_manifest,
  file.path(
    output_dir,
    "contrast_manifest.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 6. RUN AND EXPORT EACH CONTRAST
# ==============================================================================

safe_results_df <- function(res_obj) {

  out <- as.data.frame(
    res_obj,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  out$gene_id <- rownames(out)

  out <- out[
    ,
    c(
      "gene_id",
      setdiff(
        colnames(out),
        "gene_id"
      )
    ),
    drop = FALSE
  ]

  order_idx <- order(
    out$pvalue,
    -out$log2FoldChange,
    na.last = TRUE
  )

  out[
    order_idx,
    ,
    drop = FALSE
  ]
}


write_deg_sets <- function(
    res_df,
    contrast_name
) {

  # ---------------------------------------------------------------------------
  # A. Overall DEG set:
  #    raw P < 0.05 and |log2FC| >= 1
  # ---------------------------------------------------------------------------

  deg_all <- res_df[
    !is.na(res_df$pvalue) &
      res_df$pvalue < P_CUTOFF &
      abs(res_df$log2FoldChange) >= LFC_CUTOFF,
    ,
    drop = FALSE
  ]

  write.csv(
    deg_all,
    file.path(
      output_dir,
      "DEG_ALL_P005_LFC1",
      paste0(
        contrast_name,
        "_DEG_ALL.csv"
      )
    ),
    row.names = FALSE
  )

  # ---------------------------------------------------------------------------
  # B. Direction-specific, more stringent subsets:
  #    padj < 0.05 and log2FC >= 1 (UP)
  #    padj < 0.05 and log2FC <= -1 (DOWN)
  # ---------------------------------------------------------------------------

  deg_up <- res_df[
    !is.na(res_df$padj) &
      res_df$padj < PADJ_CUTOFF &
      res_df$log2FoldChange >= LFC_CUTOFF,
    ,
    drop = FALSE
  ]

  deg_down <- res_df[
    !is.na(res_df$padj) &
      res_df$padj < PADJ_CUTOFF &
      res_df$log2FoldChange <= -LFC_CUTOFF,
    ,
    drop = FALSE
  ]

  write.csv(
    deg_up,
    file.path(
      output_dir,
      "DEG_UP_PADJ005_LFC1",
      paste0(
        contrast_name,
        "_UP.csv"
      )
    ),
    row.names = FALSE
  )

  write.csv(
    deg_down,
    file.path(
      output_dir,
      "DEG_DOWN_PADJ005_LFC1",
      paste0(
        contrast_name,
        "_DOWN.csv"
      )
    ),
    row.names = FALSE
  )

  data.frame(
    contrast_name = contrast_name,
    DEG_all_P005_LFC1 = nrow(deg_all),
    UP_padj005_LFC1 = nrow(deg_up),
    DOWN_padj005_LFC1 = nrow(deg_down),
    stringsAsFactors = FALSE
  )
}


deg_summary_list <- vector(
  "list",
  nrow(contrast_manifest)
)

for (i in seq_len(nrow(contrast_manifest))) {

  numerator <- contrast_manifest$numerator[i]
  denominator <- contrast_manifest$denominator[i]
  contrast_name <- contrast_manifest$contrast_name[i]

  message(
    "DESeq2 contrast: ",
    numerator,
    " vs ",
    denominator
  )

  res <- results(
    dds,
    contrast = c(
      "condition",
      numerator,
      denominator
    ),
    alpha = P_CUTOFF
  )

  res_df <- safe_results_df(
    res
  )

  write.csv(
    res_df,
    file.path(
      output_dir,
      "all_contrasts",
      paste0(
        contrast_name,
        ".csv"
      )
    ),
    row.names = FALSE
  )

  deg_summary_list[[i]] <- write_deg_sets(
    res_df = res_df,
    contrast_name = contrast_name
  )
}

deg_summary <- do.call(
  rbind,
  deg_summary_list
)

write.csv(
  deg_summary,
  file.path(
    output_dir,
    "DEG_summary.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 7. SAVE REPRODUCIBILITY INFORMATION
# ==============================================================================

capture.output(
  sessionInfo(),
  file = file.path(
    output_dir,
    "R_sessionInfo.txt"
  )
)

message("")
message("==============================================================")
message("DESeq2 analysis completed.")
message("BioProject: PRJNA1420504")
message("Retained genes after filtering: ", nrow(count_data_filtered))
message("Number of contrasts: ", nrow(contrast_manifest))
message("")
message("DEG criteria:")
message("  Overall DEG: P < 0.05 and |log2FC| >= 1")
message("  Upregulated subset: padj < 0.05 and log2FC >= 1")
message("  Downregulated subset: padj < 0.05 and log2FC <= -1")
message("==============================================================")
